### ISSUE TITLE
stat has no option 'c' on Mac OSX

### ISSUE THREAD

**Issue by hackdefendr** [lateralblast/lunar#23]
`stat: illegal option -- c
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]`

Option -f would be used on Mac OS X.

**Comment by richardatlateralblast** [comment]
Think I need a little more information/output.

The test with "stat -c" in modules/audit_file_perms.sh should not run on OS X.

The command line you are running and some more of the output may assist. Also the version of OS X, as most of the testing has been done on later releases.

**Comment by hackdefendr** [comment]
Command line is the basic "./lunar -a".  The output I already provided, but I will provide more if you think it will help.

Start of output from the above command:

> # SYSTEM INFORMATION:
> 
> Platform:  i386
> Vendor:    Apple
> Name:      Darwin
> Version:   10.13
> Update:    2

<SNIP>

> Checking:  Application Permissions
> Checking:  File permissions on /Applications/Android File Transfer.app
> Checking:  File permissions on /Applications/App Store.app
> Checking:  File permissions on /Applications/Automator.app
> Checking:  File permissions on /Applications/Burp Suite Free Edition.app
> Checking:  File permissions on /Applications/Calculator.app
> Checking:  File permissions on /Applications/Calendar.app
> Checking:  File permissions on /Applications/Chess.app
> Checking:  File permissions on /Applications/Chicken of the VNC.app
> Checking:  File permissions on /Applications/CoRD.app
> Checking:  File permissions on /Applications/Contacts.app
> Checking:  File permissions on /Applications/Cyberduck.app
> Checking:  File permissions on /Applications/DVD Player.app
> Checking:  File permissions on /Applications/Dashboard.app
> Checking:  File permissions on /Applications/Dictionary.app
> Checking:  File permissions on /Applications/Electric Sheep.app
> Checking:  File permissions on /Applications/Etcher.app
> Checking:  File permissions on /Applications/FaceTime.app
> Checking:  File permissions on /Applications/Font Book.app
> Checking:  File permissions on /Applications/GarageBand.app
> stat: illegal option -- c
> usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
> Setting:   File /Applications/GarageBand.app to have correct permissions
> chmod: Unable to change file mode on /Applications/GarageBand.app: Operation not permitted
> Checking:  File permissions on /Applications/Gimp.app
> Checking:  File permissions on /Applications/Google Chrome.app
> Checking:  File permissions on /Applications/Image Capture.app
> Checking:  File permissions on /Applications/KeePassX.app
> Checking:  File permissions on /Applications/Keynote.app
> Checking:  File permissions on /Applications/Launchpad.app
> Checking:  File permissions on /Applications/Mail.app
> Checking:  File permissions on /Applications/Malwarebytes.app
> Checking:  File permissions on /Applications/Maps.app
> Checking:  File permissions on /Applications/Messages.app
> Checking:  File permissions on /Applications/Microsoft Excel.app
> stat: illegal option -- c
> usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
> Setting:   File /Applications/Microsoft Excel.app to have correct permissions
> chmod: Unable to change file mode on /Applications/Microsoft Excel.app: Operation not permitted

Not sure why my Mac is being detected as i386 when it is actually x86_64?

**Comment by richardatlateralblast** [comment]
Ok, I found the other reference to stat, this should now be fixed, it uses a 'stat -f %p $check_file |tail -c4' to mimic 'stat -c %a' on Linux.

i386 is the processor, i.e. uname -p, I've added the machine, i.e. uname -m, and cleaned up the description:

Processor: i386
Machine:   x86_64
Vendor:    Apple
Name:      Darwin
Version:   10.13
Update:    3

**Comment by hackdefendr** [comment]
Confirmed. Thank-you!
