### ISSUE TITLE
Line 32 error: functions/check_systemctl_service.sh

### ISSUE THREAD

**Issue by layer67tech** [lateralblast/lunar#24]
CentOS 6 system not detected due to bug in the "if condition" on line 32
file: functions/check_systemctl_service.sh

This works:
` if [ "$os_vendor" = "Centos" ] && [ "$os_version" = "7" ]; then`
      `use_systemctl="yes"`
    `fi`
    `if [ "$os_vendor" = "Red" ] && [ "$os_version" = "6" ]; then`
      `use_systemctl="no"`
    `fi`
    `if [ "$os_vendor" = "Centos" ] && [ "$os_version" = "6" ]; then`
      `use_systemctl="no"`
   ` fi`
    `if [ "$os_vendor" = "Red" ] && [ "$os_version" = 7 ]; then`
     ` use_systemctl="yes"`
   ` fi`

**Comment by richardatlateralblast** [comment]
Sorry for the slowness on replying, I tried to reproduce the problem a couple of times and couldn't. It did not run the systemctl check on Centos 6 in my test VM as intended as Centos 6 does not have systemd. 

I did however find a bug in the chkconfig script and fixed that.

If you've got some output that can give me that shows the incorrect output that may help.
