### ISSUE TITLE
Support chrony

### ISSUE THREAD

**Issue by liedekef** [lateralblast/lunar#35]
Hi,

I just tested this out and it seems like a nice tool. However, I see warnings concerning ntp in my output, but I'm using chrony (it is also the default in RHEL8). So maybe next to NTP, chrony can be supported too?

**Comment by richardatlateralblast** [comment]
I had also noticed this on RHEL 8. I've also been thinking about how I handle both ntp and chrony. I'll leave this open till I get some time to have a look.

**Comment by richardatlateralblast** [comment]
I think I've fixed this one. The NTP code needed a bit of a clean up.  I've cleaned it up and committed it. I'll do a bit more testing when I get a chance.

**Comment by richardatlateralblast** [comment]
I'll close this for now.

**Comment by richardatlateralblast** [comment]
Closed
