### ISSUE TITLE
auditd check

### ISSUE THREAD

**Issue by liedekef** [lateralblast/lunar#36]
In modules/audit_system_accounting.sh there's:

```
      service_name="sysstat"
      check_chkconfig_service $service_name 3 on
      check_chkconfig_service $service_name 5 on
      service_bname="auditd"
      check_chkconfig_service $service_name 3 on
      check_chkconfig_service $service_name 5 on
```
I think the "service_bname" needs to be "service_name" too.
Also, there's no support for systemctl in that module, so the line "check_systemctl_service enable ..." should be added too.

**Comment by richardatlateralblast** [comment]
Thanks for the fix/suggestion. I've updated this.
