### ISSUE TITLE
systemd and sysv

### ISSUE THREAD

**Issue by liedekef** [lateralblast/lunar#37]
Some modules have check_chkconfig_service, others only check_systemctl_service and some both.
I think a simple check might be used for systemctl-based OS's (systemctl does a fallback to chkconfig if needed anyway), so I'd suggest something like this:
```
if [ -f /usr/bin/systemctl ]; then
   check_systemctl_service ...
else
   check_chkconfig_service ...
fi
```
Adding that in a function check_service (with 3 options: the service name, active/disable, runlevels for sysv) would allow to make this in all modules more generic to the method being used by the OS too.

**Comment by richardatlateralblast** [comment]
Thanks. Another good suggestion. I'll leave this open till I get a chance to have a look at it.

**Comment by richardatlateralblast** [comment]
After having a look a bit more, I think this is going to be a part of a larger cleanup. Will leave it open as a todo when I get to it.

**Comment by richardatlateralblast** [comment]
Have done some work on this, not sure it's completely there, but it's definitely cleaner
