### ISSUE TITLE
Script Fails on current updated Debian Stretch

### ISSUE THREAD

**Issue by marcobelmonte** [lateralblast/lunar#4]
Hi, first - thanks for sharing your work with the community. Appreciated!

This is the output of a freshly cloned git repo on Debian Stretch:

``
root@revelaptop:/opt/src/lunar# ./lunar.sh -av

Running:   In audit mode (no changes will be made to system)
           Filesystem checks will not be done

# SYSTEM INFORMATION:

Platform:  unknown
Vendor:    Debian
Name:      Linux
Version:   testing
Update:    testing
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 324: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 344: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 347: ./lunar.sh: source: not found
./lunar.sh: 463: ./lunar.sh: funct_audit_system_all: not found
./lunar.sh: 469: ./lunar.sh: funct_audit_system_x86: not found

Tests:     0
Secure:    0
Warnings:  0
`

Let me know what info I can provide to help you although I suspect you already know... `

**Comment by richardatlateralblast** [comment]
Thanks for testing, I've seen this before with how Ubuntu / Debian map sh to bash, you might be able to get around it by running something like 'bash ./lunar.sh'.
Anyway I'll fire up a VM an see if I can replicate it and fix it. I haven't tested it on Debian for quite some time, so I'll no doubt find other things that need fixing :).

**Comment by richardatlateralblast** [comment]
This should now be fixed.

I noticed there are also new CIS benchmarks out for Debian and Ubuntu. I'll have a look through those and update the code accordingly.

**Comment by marcobelmonte** [comment]
Had to execute it with "bash ./lunar.sh -av" but it works now - thanks for the quick fix and I'll let you know of any other issues if they arise. Thanks again :-)
