### ISSUE TITLE
audit_file_perms.sh erroneously calls rpm on Debian-based systems

### ISSUE THREAD

**Issue by unixben** [lateralblast/lunar#44]
There is currently no check for specific linux distributions.

> Checking:  File permissions [This may take a while]
> ./lunar.sh: 1: rpm: not found

A check needs to go in [modules/audit_file_perms.sh](https://github.com/lateralblast/lunar/blob/c8d02c92d99d224c7dc58321be0ea4bc421ea504/modules/audit_file_perms.sh#L69)

**Comment by richardatlateralblast** [comment]
Thanks!
