### ISSUE TITLE
elfsign not available on Debian/Ubuntu based systems since ~2004 (?)

### ISSUE THREAD

**Issue by unixben** [lateralblast/lunar#48]
> Checking:  Result:    ./lunar.sh: 1: elfsign: not found

[Occurs here](https://github.com/lateralblast/lunar/blob/c289fe022dc3ed276a9122dafe70f3e2ba7090e8/modules/audit_suid_files.sh#L29)
and
[Here](https://github.com/lateralblast/lunar/blob/c289fe022dc3ed276a9122dafe70f3e2ba7090e8/modules/audit_suid_files.sh#L70)

May require installation of some ELF linter or checker such as elfutils

[Discussion on the whereabouts of elfsign.](https://lists.debian.org/debian-legal/2004/05/msg00169.html)

**Comment by richardatlateralblast** [comment]
I removed it for the moment, but I'll leave this open as a reminder I need to come up with a replacement, whether that's a hash/sum check against package repository or something else

**Comment by richardatlateralblast** [comment]
I had a look into this further and unlike Solaris the package checksums on Linux are next to useless, so will close this until I think of something better.
