### ISSUE TITLE
SSH-Setting - AllowTcpForwarding

### ISSUE THREAD

**Issue by H8to** [lateralblast/lunar#5]
Aloha,

```
Checking:  Value of "AllowTcpForwarding" is set to "yes" in /etc/ssh/sshd_config
Warning:   Parameter "AllowTcpForwarding" not set to "yes" in /etc/ssh/sshd_config [25 Warnings]
```

Shouldn't this be no in a hardened environment?

**Comment by richardatlateralblast** [comment]
Thanks. 

A long time ago, that used to be an optional test based on application requirements, e.g. swat. In cleaning up code it must have slipped back into the main tests. 

I've set it to no.

**Comment by H8to** [comment]
Good job! Thanks :)
