### ISSUE TITLE
Odd quoting in modules/audit_retry_limit.sh

### ISSUE THREAD

**Issue by unixben** [lateralblast/lunar#51]
Possible incomplete quotation on lines [12](https://github.com/lateralblast/lunar/blob/0f55ddb75d5ccd73d9d6e9ec953203a8ba794d1d/modules/audit_retry_limit.sh#L12
) and [15](https://github.com/lateralblast/lunar/blob/0f55ddb75d5ccd73d9d6e9ec953203a8ba794d1d/modules/audit_retry_limit.sh#L15).

**Comment by richardatlateralblast** [comment]
Thanks, fixed
