### ISSUE TITLE
Use of constants instead of variables (which are themselves undefined)

### ISSUE THREAD

**Issue by unixben** [lateralblast/lunar#55]
Again, since I don't use AWS, I can't check this one.
[Relevant code](https://github.com/lateralblast/lunar/blob/cea73d468aa506f2453a18c5fd3cfc2eaa91b597/modules/audit_aws_rec_monitoring.sh#L17)

**Comment by richardatlateralblast** [comment]
I suspect I coded this one late at night, I'll have to have a think about this one...

**Comment by richardatlateralblast** [comment]
I ended up commenting this out as it appears to be from another test. I need to revisit this and add all the new tests they recommend.
