### ISSUE TITLE
UsePrivilegeSeparation No < Yes < Sandbox

### ISSUE THREAD

**Issue by H8to** [lateralblast/lunar#6]
Hi there,

You put a lot of effort in this tool, great job!
I hope I can provide valuable feedback ;) 

For the ssh_config checks you check for:
`funct_file_value $check_file UsePrivilegeSeparation space yes hash`

It can also be sandbox which is even more secure then setting it to yes [man page](https://www.freebsd.org/cgi/man.cgi?sshd_config(5)).

It should see `yes` and `sandbox` as safe.

Regards,
H8

**Comment by richardatlateralblast** [comment]
Fixed.

I remember there being some issues with sandbox when I used to do OpenSSH testing, but that was a few years ago, so probably ok to use now.

The SSH support needs updating to include cipher checks. Something to add to the todo list.
