### ISSUE TITLE
problem with check_file_perms.sh

### ISSUE THREAD

**Issue by Th3V01d01001001** [lateralblast/lunar#63]
I checked some ubuntu devices lately and got many "File xxx has incorrect permissions" warnings, but the permissions and owner:group were set correct (checked it manually)
the find commend uses -depth 0 as a parameter. But I think the correct parameter is -maxdepth 0 if I'm not mistaken. I tried it and got the correct results (at least on ubuntu with bash)
With -depth 0 (depth takes no argument) I get an "find: path must precede expression: 0" error. But with 2>/dev/null as used in the command the result (variable) is empty. So the next if statement ( if [ "$check_result" != "$check_file" ]; then) will fail and the file is marked as a file with incorrect permissions.

Thx for the great tool :)

**Comment by richardatlateralblast** [comment]
Thanks, interesting, max depth achieves the same result in this case and appears to work on non GNU find, so have changed it. I've also added a check for a null result. Hopefully that fixes it. I need to test script on Ubuntu 24.04 and later, so should get to test this more thoroughly soon.
